language: java
os: linux
#sudo: false
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

notifications:
  email:
    on_success: never
    on_failure: always

addons:
  sonarcloud:
    enabled: true    
    organization: "tonikolaba-github"

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar 

