language: java
os: linux
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

notifications:
  email:
    on_success: never
    on_failure: always

install: true

script: mvn clean verify package || mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
