language: java

sudo: required

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "tonikolaba-github"
    token: $BatBat-Game
    install: true

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar


notifications:
  email:
    on_success: never
    on_failure: always

