language: java

sudo: false

jdk:
  #- oraclejdk9
  - oraclejdk8
  #- oraclejdk7

addons:
  sonarcloud:
    organization: "tonikolaba-github"
    token: $BatBat-Game

script: mvn clean install -DskipTests=true 
  #-Dmaven.javadoc.skip=true -B -V 
  #- sudo apt-get update && sudo apt-get install oracle-java8-installer
  #- java -version

notifications:
  email:
    on_success: never
    on_failure: always

